version: "3.7"
services:
  es742:
    image: elasticsearch:7.4.2
    container_name: es742
    stdin_open: true
    tty: true
    privileged: true
    volumes:
      - "./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
      - "./elasticsearch/data:/usr/share/elasticsearch/data"
      - "./elasticsearch/plugins:/usr/share/elasticsearch/plugins"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      elasticsearch:
        # ipv4_address: 10.128.0.5 # Specify a static IP address for containers for this service when joining the network.
    logging:
      driver: "json-file"
      options:
        max-size: "1g"
networks:
  elasticsearch:
    ipam:
      driver: default
      config:
        - subnet: 10.128.0.0/16